config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"

  resources :dashboard, only: [:index]

  # Login and registration
  resources :sessions, only: [:new, :create] do
    collection do
      get '/destroy', action: :destroy
    end
  end

  resources :users, only: [:new, :create, :edit, :update]

  resources :competitors
  resources :teams
  resources :team_invites do
    get :accept
  end

  resources :events, param: "event_slug", path: ""

  scope ':event_slug/' do
    resources :scheduled_events, param: "scheduled_slug", path: "", as: "scheduled_event"
  end

  scope ':event_slug/:scheduled_slug/manage', module: "manage", as: "manage_scheduled_event" do
    get '/', controller: 'manage', action: :index
    resources :teams, as: "teams"
    resources :competitors, as: "competitors"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  belongs_to :scheduled_event
  belongs_to :user

  belongs_to :team, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  audited

  validates_uniqueness_of :name, conditions: -> { active }

  scope :active, -> { where("events.deleted_at IS NULL") }

  has_many :organisers
  has_many :users, through: :organisers
  has_many :scheduled_events

  has_one_attached :banner
  has_one_attached :avatar

  def find_named(name)
    Event.where("LOWER(name) = #{name}").first
  end

  def to_param
    slug
  end
end

app/models/organiser.rb
class Organiser < ApplicationRecord
  audited
  
  belongs_to :event
  belongs_to :user

  scope :active, -> { where("organisers.deleted_at IS NOT NULL") }
end

app/models/scheduled_event.rb
class ScheduledEvent < ApplicationRecord
  audited

  belongs_to :event

  has_many :competitors
  has_many :teams

  scope :next_first, -> { order("starts_at DESC") }

  def identifier
    starts_at.strftime("on %Y/%m/%d at %H:%M")
  end

  def duration
    ends_at - starts_at
  end

  def to_param
    slug
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :scheduled_event

  has_many :members, class_name: "Competitor"
  has_many :users, through: :members

  has_many :team_invites
end

app/models/team_invite.rb
class TeamInvite < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
require 'digest/md5'

class User < ApplicationRecord
  has_secure_password
  audited

  scope :active, -> { where("users.deleted_at IS NOT NULL") }

  has_many :organisers
  has_many :events, through: :organisers

  def attending?(scheduled_event)
    scheduled_event.competitors.where(user: self).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def current_user
    @logged_in_user ||= User.find_by(id: session[:user_id])
  end

  def current_competitor
    @scheduled_event&.competitors&.where(user: current_user)&.first  
  end

  def authenticate_user!
    redirect_to new_session_url, alert: "You must be logged in to do that" unless current_user
  end

  def authenticate_organiser!
    unless current_user.events.include?(@event)
      redirect_to new_session_url, alert: "You must be an organiser to do that"
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @events = Event.all.active
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, except: [:index, :new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :authenticate_organiser!, except: [:index, :show, :new, :create]

  def index
    @events = Event.all.active
  end

  def show
    @upcoming_scheduled_events = @event.scheduled_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.slug = @event.name.parameterize

    ActiveRecord::Base.transaction do
      @event.save!
      @event.organisers.create! user: current_user
      redirect_to @event and return
    end

    render :new
  end

  def edit; end

  def update
    @event.update_attributes(event_params)
    redirect_to edit_event_path(@event), notice: "Changes saved"
  end

  private

  def find_event
    @event = Event.find_by_slug(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :banner)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new; end

  def create
    user = User.find_by(email: params[:email])
    redirect_to new_session_path, alert: "Email address not found" and return unless user

    authenticated_user = user.authenticate(params[:password])
    redirect_to new_session_path, alert: "Password incorrect" and return unless authenticated_user

    session[:user_id] = user.id

    redirect_to root_path
  end

  def destroy
    session[:user_id] = "0"
    redirect_to root_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :find_team, except: [:create]
  before_action :require_member_of_team_or_organiser, except: [:create]

  def create
    @scheduled_event = ScheduledEvent.find(params[:team][:scheduled_event_id])

    puts "sch_id: #{@scheduled_event.id}"

    ActiveRecord::Base.transaction do
      @team = @scheduled_event.teams.create!(team_params)
      @team.members << current_competitor
    end

    redirect_to scheduled_event_path(@scheduled_event.event, @scheduled_event)
  end

  def destroy
    # This action is a bit mis-named
    # The actual function is to remove a competitor from a team
    # and only remove the team if that is the last competitor
    @team.members.where(id: current_competitor.id).update_all(team_id: nil)
    @team.save!

    if @team.members.empty?
      @team.destroy!
    end

    redirect_to scheduled_event_path(@scheduled_event.event, @scheduled_event)
  end

  private

  def find_team
    @team = Team.find(params[:id])
    @scheduled_event = @team.scheduled_event
  end

  def team_params
    params.require(:team).permit(:name)
  end

  def require_member_of_team_or_organiser
    unless current_competitor.team == @team
      redirect_to @scheduled_event, error: "You must be a member of the team to edit the team"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = User.new    
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes! user_params
    redirect_to edit_user_path(@user), notice: "Changes saved"
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirm, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @logged_in_user ||= User.find_by(id: session[:user_id])
  end

  def current_competitor
    @scheduled_event&.competitors&.where(user: current_user)&.first  
  end

  def profile_picture_url
    gravtar_url
  end

  def gravtar_url
    hash = Digest::MD5.hexdigest(current_user.email)
    "https://www.gravatar.com/avatar/#{hash}"
  end

  def current_user_organiser_for?(event)
    event.organisers
      .joins(:user)
      .joins(:event)
      .where("organisers.deleted_at IS NULL")
      .where("users.deleted_at IS NULL")
      .where("events.deleted_at IS NULL")
      .where(user: current_user)
      .count > 0
  end
end

app/helpers/competitors_helper.rb
module CompetitorsHelper
end

app/helpers/organiser_panel_helper.rb
module OrganiserPanelHelper
end

app/helpers/scheduled_events_helper.rb
module ScheduledEventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_invites_helper.rb
module TeamInvitesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |f| %>
  <% unless @event.errors.empty? %>
    <%= @event.errors.full_messages.join("<br />") %>
  <% end %>

  <%= f.text_field :name, placeholder: "Name" %>

  Banner image
  <%= f.file_field :banner %>

  <% if @event.persisted? %>
    <%= f.button "Save" %>
  <% else %>
    <%= f.button "Create" %>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="surface content">
    <h1>Editing <%= @event.name %></h1>

    <%= render "form" %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-full">
  <div class="actions">
    <%= link_to "Organise an event", new_event_path, class: "button" if current_user %>
  </div>
  <section>
    <h1>
      Upcoming events
    </h1>
    
    <div class="grid-event-list">
      <% @events.each do |event| %>
        <%= link_to event, class: "surface event-tile", style: "background-image: url( #{url_for(event.banner) if event.banner.attached?} )" do %>
          <%= content_tag "span" do %>
            <%= event.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="surface content">
    <h1>Start an event</h1>

    <%= render "form" %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <% if @event.users.include?(current_user) %>
    <div class="actions">
      <%= link_to "Manage", edit_event_path(@event), class: "button" %>
      <%= link_to "Schedule an event", new_scheduled_event_path(@event), class: "button" %>
    </div>
  <% end %>

  <h1><%= @event.name %></h1>
  <section>
    <h1>
      Coming up soon
    </h1>

    <div class="grid-event-list">
      <% @upcoming_scheduled_events.each do |scheduled_event| %>
        <%= link_to scheduled_event_path(@event, scheduled_event), class: "surface event-tile", style: "background-image: url( #{url_for(@event.banner) if @event.banner.attached?} )" do %>
          <%= content_tag "span" do %>
            <%= scheduled_event.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </section>
</div>