config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"

  resources :dashboard, only: [:index]

  # Login and registration
  resources :sessions, only: [:new, :create] do
    collection do
      get '/destroy', action: :destroy
    end
  end

  resources :users, only: [:new, :create, :edit, :update]

  resources :competitors
  resources :teams
  resources :team_invites do
    get :accept
  end

  resources :events, param: "event_slug", path: ""

  scope ':event_slug/' do
    resources :scheduled_events, param: "scheduled_slug", path: "", as: "scheduled_event"
  end

  scope ':event_slug/:scheduled_slug/manage', module: "manage", as: "manage_scheduled_event" do
    get '/', controller: 'manage', action: :index
    resources :teams, as: "teams"
    resources :competitors, as: "competitors"
  end
end

app/models/scheduled_event.rb
class ScheduledEvent < ApplicationRecord
  audited

  belongs_to :event

  has_many :competitors
  has_many :teams

  scope :next_first, -> { order("starts_at DESC") }

  def identifier
    starts_at.strftime("on %Y/%m/%d at %H:%M")
  end

  def duration
    ends_at - starts_at
  end

  def to_param
    slug
  end
end

app/controllers/scheduled_events_controller.rb
class ScheduledEventsController < ApplicationController
  before_action :find_scheduled_event, only: [:show, :edit, :update, :new]
  skip_before_action :authenticate_user!, only: [:show]
  before_action :authenticate_organiser!, except: [:show, :create]

  def show
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    @rendered_description = markdown.render(@scheduled_event.description || "")
  end

  def new
    @scheduled_event = @event.scheduled_events.new
  end

  def create
    @event = Event.find(params[:scheduled_event][:event_id])
    @scheduled_event = @event.scheduled_events.new(scheduled_event_params)
    @scheduled_event.slug = @scheduled_event.name.parameterize

    if @scheduled_event.save
      redirect_to scheduled_event_path(@event, @scheduled_event) and return
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @scheduled_event.update_attributes(scheduled_event_params)
      redirect_to scheduled_event_path(@event, @scheduled_event), notice: "Changes saved" and return
    else
      render :edit
    end
  end

  private

  def find_scheduled_event
    @event = Event.find_by_slug(params[:event_id])
    @scheduled_event = @event.scheduled_events.find_by_slug(params[:scheduled_id])
  end

  def scheduled_event_params
    params.require(:scheduled_event).permit(
      :name,
      :starts_at,
      :ends_at,
      :location_text,
      :description,
      :lat,
      :long,
      :maximum_team_size,
      :signups_open_at,
      :signups_close_at
    )
  end
end

app/helpers/scheduled_events_helper.rb
module ScheduledEventsHelper
end

app/views/scheduled_events/_event_schedule.html.erb
<div class="event-schedule">
  <div>Starts at <%= @scheduled_event.starts_at.strftime("%l:%M%P %A #{@scheduled_event.starts_at.day.ordinalize} %B %Y") %></div>
  <div>Runs for <%= distance_of_time_in_words(@scheduled_event.duration) %></div>
</div>

app/views/scheduled_events/_form.html.erb
<% if @scheduled_event.persisted? %>
  <% @url = scheduled_event_path(@event, @scheduled_event) %>
<% else %>
  <% @url = scheduled_events_path %>
<% end %>

<%= form_with model: @scheduled_event, url: @url, local: true do |f| %>
  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.label :name %>
  <%= f.text_field :name, disabled: @scheduled_event.persisted? %>

  <%= f.label :starts_at %>
  <%= f.datetime_field :starts_at, required: true %>

  <%= f.label :ends_at %>
  <%= f.datetime_field :ends_at, required: true %>

  <%= f.label :location_text, "Description of location" %>
  <%= f.text_area :location_text, required: true %>

  <%= f.label :description, "Description / Content of page" %>
  <%= f.text_area :description %>

  <%= f.label "Location (Coordinates)" %>
  <%= f.text_field :lat, placeholder: "Latitude" %>
  <%= f.text_field :long, placeholder: "Longitide" %>

  <%= f.label "Maximum team size?" %>
  <%= f.text_field :maximum_team_size %>

  <%= f.label :signups_open_at %>
  <%= f.datetime_field :signups_open_at, required: true %>

  <%= f.label :signups_close_at %>
  <%= f.datetime_field :signups_close_at, required: true %>

  <% if @scheduled_event.persisted? %>
    <%= f.button "Save" %>
  <% else %>
    <%= f.button "Create" %>
  <% end %>
<% end %>

app/views/scheduled_events/_teams.html.erb
<% if current_user %>
      <section>
        <h1>Team</h1>

        <% if current_competitor&.team %>
            You're competiting in team <b><%= current_competitor.team.name %></b>

            <%= form_with url: team_path(current_competitor.team), method: :delete, local: true do |f| %>
              <%= f.button "Leave team" %>
            <% end %>

            <p>
              <%= form_with url: team_invites_path, local: true do |f| %>
                <%= f.hidden_field :team_id, value: current_competitor.team.id %>
                <%= f.text_field :email, placeholder: "Email address" %>
                <%= f.button "Invite user" %>
              <% end %>

              <% if current_competitor.team.team_invites.any? %>
                <br />
                Pending invites to Golden Eagle<br />
                <ul>
                  <% current_competitor.team.team_invites.each do |invite| %>
                    <li><%= invite.user.name %> invited <%= invite.invited_email %> <%= distance_of_time_in_words(Time.now, invite.created_at) %> ago</li>
                  <% end %>
                </ul>
              <% end %>
            </p>
        <% else %>
          Create a team

          <%= form_with model: @scheduled_event.teams.new, url: teams_path, local: true do |f| %>
            <%= f.hidden_field :scheduled_event_id, value: @scheduled_event.id %>
            <%= f.text_field :name, placeholder: "Team name" %>
            <%= f.button "Create team" %>
          <% end %>
        <% end %>
      </section>
    <% end %>

app/views/scheduled_events/edit.html.erb
<div class="container">
  <div class="surface content">
    <h1>Editing <%= @event.name %> for <%= @scheduled_event.starts_at %></h1>
    <%= render "form" %>
  </div>
</div>

app/views/scheduled_events/new.html.erb
<div class="surface">
  <h1>Schedule the new <%= @event.name %></h1>
  <%= render "form" %>
</div>

app/views/scheduled_events/show.html.erb
<% if @event.banner.attached? %>
  <div class="banner" style="background-image: url('<%= url_for(@event.banner) %>');"></div>
<% else %>
  <div class="banner"></div>
<% end %>
<div class="container grid-event">
  <% if current_user_organiser_for?(@event) %>
  <div class="management">
    <span>You're an organiser for <%= @event.name %>.</span>
    <%= link_to "Manage", manage_scheduled_event_path, class: "button" %>
  </div>
  <% end %>

  <div class="surface event-control-bar">
    <%= image_tag "placeholder-event.svg", class: "event-avatar" %>
    <div class="control-bar-details">
      <%= render partial: "event_schedule" %>

      <% if current_competitor %>
        <%= form_with url: competitor_path(current_competitor), local: true, method: :delete do |f| %>
          <%= f.button "Attending", class: "button stateful active affirmative", data: { action: "Leave" } %>
        <% end %>
      <% else %>
        <%= form_with url: competitors_path, local: true do |f| %>
          <%= f.hidden_field :scheduled_event, value: @scheduled_event.id %>
          <%= f.button "Attend" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="surface main content">
    <h1><%= @event.name %></h1>

    <%= render partial: "event_schedule" %>

    <div class="subheading">
      <%= @scheduled_event.location_text %>
    </div>

    <div class="description">
      <%= raw @rendered_description %>
    </div>

    <!-- <%= render "teams" %> -->
  </div>

  <aside class="surface">
    <%= content_tag 'div', '', class: "map", data: {lat: @scheduled_event.lat, long: @scheduled_event.long} %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDiBkB9k8UQh4nAS8X9LrEYfNn25MnwGZY&callback=initMap"></script>
  </aside>
</div>